AWSTemplateFormatVersion: "2010-09-09"
Description: Static website hosting bucket

Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html

Outputs:
  BucketName:
    Value: !Ref StaticSiteBucket
